export const events = [
	{ english: 'murder', korean: '살인', category: 'event' },
	{ english: 'robbery', korean: '강도', category: 'event' },
	{ english: 'kidnapping', korean: '납치', category: 'event' },
	{ english: 'betrayal', korean: '배신', category: 'event' },
	{ english: 'terrorist attack', korean: '테러 공격', category: 'event' },
	{ english: 'space mission', korean: '우주 여행', category: 'event' },
	{ english: 'time travel', korean: '시간 여행', category: 'event' },
	{ english: 'alien invasion', korean: '외계인 침공', category: 'event' },
	{ english: 'virus outbreak', korean: '바이러스 발생', category: 'event' },
	{
		english: 'supernatural event',
		korean: '초자연적인 사건',
		category: 'event',
	},
	{ english: 'treasure hunt', korean: '보물 탐험', category: 'event' },
	{ english: 'political scandal', korean: '정치 스캔들', category: 'event' },
	{ english: 'epic battle', korean: '대규모 전투', category: 'event' },
	{
		english: 'sports championship',
		korean: '스포츠 챔피언십',
		category: 'event',
	},
	{ english: 'great flood', korean: '대홍수', category: 'event' },
	{ english: 'robot uprising', korean: '로봇의 반란', category: 'event' },
	{ english: 'natural disaster', korean: '자연 재해', category: 'event' },
	{ english: 'high-speed chase', korean: '고속 추격전', category: 'event' },
	{ english: 'family reunion', korean: '가족 상봉', category: 'event' },
	{
		english: 'lost in the wilderness',
		korean: '황야에서 길을 잃다',
		category: 'event',
	},
	{ english: 'medical emergency', korean: '의료 비상사태', category: 'event' },

	{
		english: 'superhero origin story',
		korean: '슈퍼히어로 탄생 이야기',
		category: 'event',
	},
	{ english: 'time loop', korean: '타임 루프', category: 'event' },
	{ english: 'detective investigation', korean: '수사', category: 'event' },
	{
		english: 'treasure island adventure',
		korean: '보물섬 모험',
		category: 'event',
	},
	{
		english: 'supernatural possession',
		korean: '초자연적인 소유',
		category: 'event',
	},
	{
		english: 'battle for the throne',
		korean: '왕좌 전쟁',
		category: 'event',
	},
	{ english: 'archaeological dig', korean: '고고학 발굴', category: 'event' },
	{ english: 'space battle', korean: '우주 전투', category: 'event' },
	{ english: 'zombie outbreak', korean: '좀비', category: 'event' },
	{ english: 'stock market crash', korean: '주식시장 붕괴', category: 'event' },
	{ english: 'falling in love', korean: '사랑에 빠지다', category: 'event' },
	{ english: 'getting a promotion', korean: '승진하기', category: 'event' },
	{ english: 'winning the lottery', korean: '복권 당첨', category: 'event' },
	{ english: 'surprise party', korean: '깜짝 파티', category: 'event' },
	{ english: 'beach vacation', korean: '해변 휴가', category: 'event' },
	{ english: 'family reunion', korean: '가족 재회', category: 'event' },
	{ english: 'summer camp', korean: '여름 캠프', category: 'event' },
	{ english: 'holiday celebration', korean: '휴일 축하', category: 'event' },
	{
		english: 'starting a new job',
		korean: '새로운 직장 시작',
		category: 'event',
	},
	{ english: 'getting married', korean: '결혼', category: 'event' },
	{
		english: 'finding a lost item',
		korean: '분실물을 찾다',
		category: 'event',
	},
	{ english: 'birth of a child', korean: '아이 탄생', category: 'event' },
	{
		english: 'receiving a scholarship',
		korean: '장학금을 받다',
		category: 'event',
	},
	{
		english: 'graduating from school',
		korean: '학교 졸업',
		category: 'event',
	},
	{ english: 'performing on stage', korean: '무대 공연', category: 'event' },
	{
		english: 'achieving a personal goal',
		korean: '개인적 목표 달성',
		category: 'event',
	},
	{ english: 'overcoming a fear', korean: '공포 극복', category: 'event' },
	{
		english: 'unexpected visit from a friend',
		korean: '친구의 뜻밖 방문',
		category: 'event',
	},
	{
		english: 'successful business venture',
		korean: '성공적인 사업',
		category: 'event',
	},
	{
		english: "saving someone's life",
		korean: '누군가의 생명 구하기',
		category: 'event',
	},
	{
		english: 'making new friends',
		korean: '새로운 친구 만들기',
		category: 'event',
	},
	{
		english: 'winning a sports competition',
		korean: '스포츠 대회 우승',
		category: 'event',
	},
	{
		english: 'finding a new hobby',
		korean: '새로운 취미 발견',
		category: 'event',
	},
	{
		english: 'moving to a new city',
		korean: '새로운 도시로 이사',
		category: 'event',
	},
	{ english: 'retiring from work', korean: '은퇴', category: 'event' },
	{ english: 'adopting a pet', korean: '애완동물 입양', category: 'event' },
	{
		english: 'completing a marathon',
		korean: '마라톤 완주',
		category: 'event',
	},
	{
		english: 'reuniting with a loved one',
		korean: '사랑하는 사람과 재회',
		category: 'event',
	},
	{
		english: 'finding true happiness',
		korean: '진정한 행복 찾기',
		category: 'event',
	},
	{
		english: 'starting a family',
		korean: '가족을 시작하다',
		category: 'event',
	},
];

export const backgrounds = [
	{ english: 'school', korean: '학교', category: 'background' },
	{ english: 'city', korean: '도시', category: 'background' },
	{ english: 'jungle', korean: '정글', category: 'background' },
	{ english: 'forest', korean: '숲', category: 'background' },
	{ english: 'desert', korean: '사막', category: 'background' },
	{ english: 'space station', korean: '우주 정거장', category: 'background' },
	{ english: 'laboratory', korean: '연구실', category: 'background' },
	{ english: 'castle', korean: '성', category: 'background' },
	{ english: 'beach', korean: '해변', category: 'background' },
	{ english: 'island', korean: '섬', category: 'background' },
	{ english: 'mountain', korean: '산', category: 'background' },
	{ english: 'farm', korean: '농장', category: 'background' },
	{ english: 'spaceship', korean: '우주선', category: 'background' },
	{ english: 'prison', korean: '감옥', category: 'background' },
	{ english: 'haunted mansion', korean: '유령 궁전', category: 'background' },
	{ english: 'small town', korean: '작은 마을', category: 'background' },
	{ english: 'village', korean: '마을', category: 'background' },
	{ english: 'underwater', korean: '수중', category: 'background' },
	{ english: 'amusement park', korean: '놀이 공원', category: 'background' },
	{ english: 'circus', korean: '서커스', category: 'background' },
	{ english: 'museum', korean: '박물관', category: 'background' },
	{ english: 'hospital', korean: '병원', category: 'background' },
	{ english: 'theater', korean: '극장', category: 'background' },
	{
		english: 'apartment building',
		korean: '아파트 건물',
		category: 'background',
	},
	{ english: 'cruise ship', korean: '크루즈선', category: 'background' },
	{ english: 'restaurant', korean: '레스토랑', category: 'background' },
	{ english: 'airport', korean: '공항', category: 'background' },
	{ english: 'shopping mall', korean: '쇼핑몰', category: 'background' },
	{ english: 'casino', korean: '카지노', category: 'background' },
	{ english: 'ski resort', korean: '스키 리조트', category: 'background' },
	{ english: 'art gallery', korean: '미술관', category: 'background' },
	{ english: 'office building', korean: '사무실 건물', category: 'background' },
	{ english: 'theme park', korean: '테마파크', category: 'background' },
	{ english: 'space shuttle', korean: '우주선', category: 'background' },
	{ english: 'battlefield', korean: '전장', category: 'background' },
	{ english: 'summer camp', korean: '여름캠프', category: 'background' },
	{ english: 'haunted forest', korean: '괴담의 숲', category: 'background' },
	{ english: 'mansion', korean: '저택', category: 'background' },
	{ english: 'train station', korean: '기차역', category: 'background' },
	{ english: 'carnival', korean: '카니발', category: 'background' },
	{ english: 'submarine', korean: '잠수함', category: 'background' },
	{ english: 'jungle temple', korean: '밀림 사원', category: 'background' },
	{
		english: 'abandoned warehouse',
		korean: '버려진 창고',
		category: 'background',
	},
	{
		english: 'laboratory complex',
		korean: '연구소 복합 건물',
		category: 'background',
	},
	{ english: 'university', korean: '대학교', category: 'background' },
	{ english: 'concert hall', korean: '콘서트홀', category: 'background' },
	{
		english: 'mansion in the woods',
		korean: '숲 속 저택',
		category: 'background',
	},
	{ english: 'TV studio', korean: 'TV 스튜디오', category: 'background' },
	{ english: 'radio station', korean: '라디오 방송국', category: 'background' },
	{ english: 'volcano', korean: '화산', category: 'background' },
];

export const genres = [
	{ english: 'romance', korean: '로맨스', category: 'genre' },
	{ english: 'comedy', korean: '코미디', category: 'genre' },
	{ english: 'horror', korean: '호러', category: 'genre' },
	{ english: 'mystery', korean: '미스터리', category: 'genre' },
	{ english: 'science fiction', korean: '공상 과학', category: 'genre' },
	{ english: 'fantasy', korean: '판타지', category: 'genre' },
	{ english: 'drama', korean: '드라마', category: 'genre' },
	{ english: 'action', korean: '액션', category: 'genre' },
	{ english: 'thriller', korean: '스릴러', category: 'genre' },
	{ english: 'historical fiction', korean: '역사 소설', category: 'genre' },
	{ english: 'western', korean: '웨스턴', category: 'genre' },
	{ english: 'crime', korean: '범죄', category: 'genre' },
	{ english: 'adventure', korean: '모험', category: 'genre' },
	{ english: 'animation', korean: '애니메이션', category: 'genre' },
	{ english: 'musical', korean: '뮤지컬', category: 'genre' },
	{ english: 'war', korean: '전쟁', category: 'genre' },
	{ english: 'documentary', korean: '다큐멘터리', category: 'genre' },
	{ english: 'superhero', korean: '슈퍼히어로', category: 'genre' },
	{ english: 'disaster', korean: '재해', category: 'genre' },
	{ english: 'sports', korean: '스포츠', category: 'genre' },
	{ english: 'noir', korean: '느와르', category: 'genre' },
	{ english: 'teen', korean: '청소년', category: 'genre' },
	{ english: 'science', korean: '과학', category: 'genre' },
	{ english: 'travel', korean: '여행', category: 'genre' },
	{ english: 'medical', korean: '의학', category: 'genre' },
	{ english: 'cyberpunk', korean: '사이버펑크', category: 'genre' },
	{ english: 'time travel', korean: '시간 여행', category: 'genre' },
];

export const characters = [
	{ english: 'Detective', korean: '수사관', category: 'character' },
	{ english: 'Soldier', korean: '군인', category: 'character' },
	{ english: 'Writer', korean: '작가', category: 'character' },
	{ english: 'Teacher', korean: '교사', category: 'character' },
	{ english: 'Scientist', korean: '과학자', category: 'character' },
	{ english: 'Musician', korean: '음악가', category: 'character' },
	{ english: 'Doctor', korean: '의사', category: 'character' },
	{ english: 'Lawyer', korean: '변호사', category: 'character' },
	{ english: 'Athlete', korean: '운동선수', category: 'character' },
	{ english: 'Chef', korean: '요리사', category: 'character' },
	{ english: 'Police officer ', korean: '경찰관', category: 'character' },
	{ english: 'Artist', korean: '예술가', category: 'character' },
	{ english: 'Journalist', korean: '저널리스트', category: 'character' },
	{ english: 'Engineer', korean: '엔지니어', category: 'character' },
	{ english: 'Entrepreneur', korean: '기업가', category: 'character' },
	{ english: 'Actor/actress', korean: '배우', category: 'character' },
	{ english: 'Inventor', korean: '발명가', category: 'character' },
	{ english: 'Pilot', korean: '조종사', category: 'character' },
	{ english: 'Secret agent', korean: '비밀요원', category: 'character' },
	{ english: 'Spy', korean: '스파이', category: 'character' },
];

export const themes = [
	{ english: 'love', korean: '사랑', category: 'theme' },
	{ english: 'loss', korean: '상실', category: 'theme' },
	{ english: 'family', korean: '가족', category: 'theme' },
	{ english: 'identity', korean: '정체성', category: 'theme' },
	{ english: 'friendship', korean: '우정', category: 'theme' },
	{ english: 'betrayal', korean: '배신', category: 'theme' },
	{ english: 'redemption', korean: '구원', category: 'theme' },
	{ english: 'survival', korean: '생존', category: 'theme' },
	{ english: 'coming of age', korean: '성장', category: 'theme' },
	{ english: 'good vs. evil', korean: '선과 악', category: 'theme' },
	{ english: 'power', korean: '권력', category: 'theme' },
	{ english: 'ambition', korean: '야망', category: 'theme' },
	{ english: 'morality', korean: '도덕성', category: 'theme' },
	{ english: 'justice', korean: '정의', category: 'theme' },
	{ english: 'change', korean: '변화', category: 'theme' },
	{ english: 'sacrifice', korean: '희생', category: 'theme' },
	{ english: 'transformation', korean: '변형', category: 'theme' },
	{ english: 'secrets', korean: '비밀', category: 'theme' },
	{ english: 'discovery', korean: '발견', category: 'theme' },
	{ english: 'nostalgia', korean: '향수', category: 'theme' },
	{ english: 'fear', korean: '공포', category: 'theme' },
	{ english: 'forgiveness', korean: '용서', category: 'theme' },
	{ english: 'acceptance', korean: '인정', category: 'theme' },
	{ english: 'individuality', korean: '개성', category: 'theme' },
	{ english: 'passion', korean: '열정', category: 'theme' },
	{ english: 'truth', korean: '진실', category: 'theme' },
	{ english: 'war', korean: '전쟁', category: 'theme' },
	{ english: 'peace', korean: '평화', category: 'theme' },
	{ english: 'hope', korean: '희망', category: 'theme' },
	{ english: 'oppression', korean: '억압', category: 'theme' },
	{ english: 'rebellion', korean: '반란', category: 'theme' },
	{ english: 'time', korean: '시간', category: 'theme' },
	{ english: 'memory', korean: '기억', category: 'theme' },
	{ english: 'religion', korean: '종교', category: 'theme' },
	{ english: 'destiny', korean: '운명', category: 'theme' },
	{ english: 'technology', korean: '기술', category: 'theme' },
	{ english: 'environmentalism', korean: '환경주의', category: 'theme' },
	{ english: 'social justice', korean: '사회정의', category: 'theme' },
	{ english: 'humanity', korean: '인간성', category: 'theme' },
	{ english: 'isolation', korean: '고립', category: 'theme' },
	{ english: 'human nature', korean: '인간의 본성', category: 'theme' },
	{ english: 'nostalgia', korean: '회상', category: 'theme' },
	{ english: 'dreams', korean: '꿈', category: 'theme' },
	{ english: 'aging', korean: '노화', category: 'theme' },
	{ english: 'illusion', korean: '환영', category: 'theme' },
	{ english: 'transcendence', korean: '초월', category: 'theme' },
	{ english: 'heroism', korean: '영웅성', category: 'theme' },
	{ english: 'growth', korean: '성장', category: 'theme' },
	{ english: 'manipulation', korean: '조작', category: 'theme' },
	{ english: 'competition', korean: '경쟁', category: 'theme' },
];
